updated start

diff --git a/trunk/start b/trunk/start
--- a/trunk/start
+++ b/trunk/start
@@ -8,12 +8,34 @@ if [ $# -ne 1 ]; then
     exit 1
 fi
 
+# Taken from http://pypi.python.org/pypi/desktop/0.3
+linux_open()
+{
+    if [ -n "$GNOME_DESKTOP_SESSION_ID" ]; then
+        if which gvfs-open > /dev/null; then
+            echo "gvfs-open"
+        else
+            echo "gnome-open"
+        fi
+    elif [ -n "$KDE_FULL_SESSION" ]; then
+        echo "kfmclient exec"
+    elif xprop -root _DT_SAVE_MODE 2>&1 | grep -iq xfce; then
+        echo "exo-open"
+    else
+        echo ""
+    fi
+}
+
 case `uname` in
-    Linux) open=exo-open;;
+    Linux) open=`linux_open`;;
     Darwin) open=open;;
     CYGWIN*) open=cygstart;;
     MINGW*) open=start;;
-    *) echo "error: no start program for `uname` platform" 1>&2; exit 1;;
 esac
+
+if [ -z "$open" ]; then
+    echo "error: no start program for `uname` platform" 1>&2
+    exit 1
+fi
 
 $open "$1" > /dev/null 2>&1
